name: CI on ubuntu-latest

on:
  push:
    branches: [ main, development, tests_fixes ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install -Dmaven.test.skip=true

      - name: Run automation tests with latest ngrok-spring-boot-starter version on test-app and spring-boot v2
        working-directory: ./.github/test-app-sb-2x/
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: mvn --batch-mode --no-transfer-progress test

      - name: Run automation tests with latest ngrok-spring-boot-starter version on test-app and spring-boot v3
        working-directory: ./.github/test-app-sb-3x/
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: mvn --batch-mode --no-transfer-progress test
