name: CI on Windows with Spring Boot 3 and JDK 17

on:
  push:
    branches: [ spring_boot_3 ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  test-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
        # install starter in local .m2
      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install -DskipTests
        # spring boot 3 web tests setup
      - name: Set up ngrok auth to token application.properties of test-app-spring-boot-3-web
        run: |
               printf ${{secrets.NGROK_AUTH_TOKEN_PROPERTY}} >> .github/test-app-spring-boot-3-web/src/test/resources/application.properties
        shell: bash
        # spring boot 3 web tests execution
      - name: Run automation tests with latest ngrok-spring-boot-starter on test-app-spring-boot-3-web
        working-directory: ./.github/test-app-spring-boot-3-web/
        run: mvn --batch-mode --no-transfer-progress test
        # spring boot 3 reactive tests setup
      - name: Set up ngrok auth token to application.properties of test-app-spring-boot-3-reactive
        run: |
               printf ${{secrets.NGROK_AUTH_TOKEN_PROPERTY}} >> .github/test-app-spring-boot-3-reactive/src/test/resources/application.properties
        shell: bash
        # spring boot 3 reactive tests execution
      - name: Run automation tests with latest ngrok-spring-boot-starter on test-app-spring-boot-3-reactive
        working-directory: ./.github/test-app-spring-boot-3-reactive/
        run: mvn --batch-mode --no-transfer-progress test
