name: spring-boot 3 web JDK17 @ macOS

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  test-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install -DskipTests
      - name: Run automation tests with latest ngrok-spring-boot-starter on test-app-spring-boot-3-web
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        working-directory: ./.github/test-app-spring-boot-3-web/
        run: mvn --batch-mode --no-transfer-progress test
