name: CI on ubuntu-latest

on:
  push:
    branches: [ main, development, tests_fixes ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install -Dmaven.test.skip=true

      - name: Add ngrok auth token application.properties
        run: |
          printf ${{secrets.NGROK_AUTH_TOKEN_PROPERTY}} >> .github/test-app/src/test/resources/application.properties
        shell: bash

      - name: Run automation tests with latest ngrok-spring-boot-starter version on test-app
        working-directory: ./.github/test-app/
        run: mvn --batch-mode --no-transfer-progress test