name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  release-github-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set version from git tag
        run: mvn -B -ntp versions:set -DgenerateBackupPoms=false -DnewVersion="$TAG"

      - name: Build package
        run: mvn -B -ntp package

      - name: Publish to Maven Central
        uses: jskov/action-maven-publish@8145b6173999b6367355a220c2cd961f54e6b259
        with:
          portal_username: ${{ secrets.PORTAL_USERNAME }}
          portal_token: ${{ secrets.PORTAL_TOKEN }}
          signing_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          signing_key_secret: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          search_directory: '.'
          target_action: 'promote_or_keep'
          log_level: 'info'
          companion_suffixes: '.jar, -javadoc.jar, -sources.jar'

      - name: Add jar to Github Release
        uses: svenstaro/upload-release-action@v2
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/ngrok-spring-boot-starter-${{ env.TAG }}.jar
          asset_name: ngrok-spring-boot-starter-${{ env.TAG }}.jar
          tag: ${{ github.ref }}
